### ISSUE TITLE
Acme_* modules should have configurable timeouts

### ISSUE THREAD

**Issue by JonasVerhofste** [ansible-collections/community.crypto#447]
##### SUMMARY
As far as I can tell, all `acme_`-modules use the standard `fetch_url` timeout, [which is 10 seconds](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/urls.py#L1729). (They all call the [acme-util](https://github.com/ansible-collections/community.crypto/blob/main/plugins/module_utils/acme/acme.py))
This timeout should be configurable in case of a slow responding ACME server.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
acme_account
acme_account_info
acme_certificate
acme_certificate_revoke
acme_challenge_cert_helper
acme_inspect

##### ADDITIONAL INFORMATION
I'm not entirely sure if this should be a global variable somehow or should be set at the module level on a per task-basis?
I've hacked our local ansible instance and have confirmed that changing the default to something higher makes 95% of our requests succeed again. (many were failing because our cert provider is having issues..)

Would gladly whip up a PR, but I'm unsure what the best location would be to set the timeout.

**Comment by felixfontein** [comment]
> I'm not entirely sure if this should be a global variable somehow or should be set at the module level on a per task-basis?

The best thing would be to add it to the `acme` docs fragment (https://github.com/ansible-collections/community.crypto/blob/main/plugins/doc_fragments/acme.py#L13) and the module_utils (https://github.com/ansible-collections/community.crypto/blob/main/plugins/module_utils/acme/acme.py#L332) so that it can be specified for every ACME module task. The Ansible equivalent to global variable would then be using module defaults (there is a community.crypto.acme module defaults group for all ACME modules, except acme_challenge_cert_helper, but that doesn't do any HTTP requests anyway and also doesn't use the `acme` doc fragment / shared argspec).

If you'd like to create a PR, that would be great!

**Comment by JonasVerhofste** [comment]
Ah, you just provided me with the link I was missing. PR incoming!
