### ISSUE TITLE
Password not working on SSH login

### ISSUE THREAD

**Issue by itsjustme187** [ansible-collections/community.crypto#812]
I have RedHat 8.8 after install and LUKS setup I changed the HOST name. After changing the host name SSH doesn't allow my password to work anymore. Is there anyplace on LUKS that would cause a conflict to happen when changing hostname's or specific locations to edit hostname? When checking Hostname LUKS still has old hostname listed.

**Comment by felixfontein** [comment]
Hi, it seems you have a general question on using some Linux tools. This is not a support channel for these tools, but this repository is for the Ansible collection community.crypto which provides Ansible modules and plugins to manage some of these tools. There are better places for your question. (I don't know a specific one though. Maybe check out the user groups of the Linux distribution you're using? Resp. since you're apparently using RHEL, you should ask RH support.)

About your specific quesion: usually LUKS has nothing to do with SSH, and I've never seen LUKS having anything to do with hostnames. (With the exception that the LVM/LUKS volume is sometimes named after the host, but it could also have a very different name.)
